language: bash
services: docker

install:
  - docker pull tianon/markdownfmt
  - docker pull tianon/ymlfmt

script:
  - .travis/check-markdownfmt.sh
  - .travis/check-ymlfmt.sh
  - .travis/check-short.sh
  - .travis/check-required-files.sh
  - .travis/check-pr-no-readme.sh
