language: go

sudo: false

install:
  - .travis/get-markdownfmt.sh

script:
  - .travis/check-markdownfmt.sh
  - .travis/check-short.sh
  - .travis/check-required-files.sh
  - .travis/check-pr-no-readme.sh
