#!/bin/bash
set -eo pipefail

cd "$(dirname "$(readlink -f "$BASH_SOURCE")")"
helperDir='.template-helpers'

repos=( "$@" )
if [ ${#repos[@]} -eq 0 ]; then
	repos=( */ )
fi
repos=( "${repos[@]%/}" )

for repo in "${repos[@]}"; do
	echo -n "$repo ... "
	{
		echo "<!-- THIS FILE IS GENERATED BY '$helperDir/generate-tag-details.sh' -->"
		echo
		"$helperDir/generate-tag-details.sh" "$repo"
	} > "$repo/tag-details.md"
	echo 'done'
done
