nginx:
    image: nginx:latest
    volumes:
        - "/path/to/nginx.conf:/etc/nginx/nginx.conf:ro"
        - "/path/to/project:/home/docker:ro"
    links:
        - "hhvm:hhvm"

hhvm:
    image: hhvm:latest
    volumes:
        - "/path/to/project:/home/docker:rw"