# Use root/example as user/password credentials

services:

  db:
    image: mariadb:11.7
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example

  adminer:
    image: adminer:4.17.1
    restart: always
    ports:
      - 8080:8080
