# Use root/example as user/password credentials

services:

  db:
    image: mariadb:11.7-ubi
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    ports:
      - 3306:3306

  adminer:
    image: adminer:4.17.1
    restart: always
    ports:
      - 8080:8080
