# Use root/example as user/password credentials
version: '3.1'

services:

    db:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: example

    adminer:
        image: adminer
        ports:
            - 8080:8080

