# Use postgres/example user/password credentials
version: '3.1'

services:

    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: example

    adminer:
        image: adminer
        ports:
            - 8080:8080
